### ISSUE TITLE
Endereçamento de email invalido 

### ISSUE THREAD

**Issue by mulliru** [MatheusHenriqueNF/MatheusHenriqueNF#1]
o endereçamento do seu email no readme está errado, deve usar o mail mailto. Abaixo um exemplo de como deve ser colocado no código:

`mailto:matheus.henrique26@unifesp.br`

em seu código deverá ser substituido da seguinte maneira:
`[![GMAIL](https://img.shields.io/badge/Gmail-D14836?style=for-the-badge&logo=gmail&logoColor=white)](mailto:matheus.henrique26@unifesp.br)`

**Comment by MatheusHenriqueNF** [comment]
Obrigado!
